// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDViHlRjGYQAEAA8XnEehf5-GDpRyjEjyQ',
    appId: '1:349432574858:web:293815bf1cd0ad89530e73',
    messagingSenderId: '349432574858',
    projectId: 'fitkhao-f0135',
    authDomain: 'fitkhao-f0135.firebaseapp.com',
    storageBucket: 'fitkhao-f0135.firebasestorage.app',
    measurementId: 'G-HT9T7GN9WD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzWEt7cbt0Bh40O2PrYTnB-DTObZF7D5Q',
    appId: '1:349432574858:android:d2e449f614d7cd0d530e73',
    messagingSenderId: '349432574858',
    projectId: 'fitkhao-f0135',
    storageBucket: 'fitkhao-f0135.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4vvUyzw0VD-0K9F9FaiP1sNWHDRLOk0k',
    appId: '1:349432574858:ios:cbe8290cca87ad39530e73',
    messagingSenderId: '349432574858',
    projectId: 'fitkhao-f0135',
    storageBucket: 'fitkhao-f0135.firebasestorage.app',
    iosBundleId: 'com.example.fitkhaoUser',
  );
}
